umijs/father

src/build.ts
src/doc.ts

refactor: ease troubleshooting while missing tsconfig.json in typescript based project

---

bin/father.js
package.json
src/test.ts

``` bash
father test
father test --coverage
```

feat: Integrate with `umi-test`

---

package.json
src/fixtures/build/rollup-svgr/.umirc.library.js
src/fixtures/build/rollup-svgr/dist/index.esm.js
src/fixtures/build/rollup-svgr/expected/index.esm.js
src/fixtures/build/rollup-svgr/package.json
src/fixtures/build/rollup-svgr/src/index.jsx
src/fixtures/build/rollup-svgr/src/menu.svg
src/getRollupConfig.ts
yarn.lock

feat: support convert svg to react component

---

package.json

update docz-theme-umi to 2.0.0

dep: update docz-theme-umi to 2.0.0

---

packages/father-build/src/babel.ts

fix: browserFiles don't match in windows since the path problem

---

README.md
packages/father-build/src/babel.ts
packages/father-build/src/fixtures/build/target-node-version/.fatherrc.js
packages/father-build/src/fixtures/build/target-node-version/expected/es/index.js
packages/father-build/src/fixtures/build/target-node-version/expected/lib/index.js
packages/father-build/src/fixtures/build/target-node-version/src/index.js
packages/father-build/src/getBabelConfig.ts
packages/father-build/src/getRollupConfig.ts
packages/father-build/src/schema.ts
packages/father-build/src/types.d.ts

feat: support specify node version with opts.nodeVersion

---

packages/father-build/src/types.d.ts
packages/father/index.d.ts
packages/father/src/doc/index.ts

fix: typing

---

packages/father/src/doc/storybook-webpack.ts

fix: Storybook miss typescript config

---

packages/father-build/package.json

dep: upgrade chokidar to 3.0.2 to fix windows problem

---

packages/father/src/preCommit.ts

ref: https://github.com/react-component/field-form/pull/20/files#r303360337

add `preCommit` missing examples

---

packages/father/src/doc/storybook.ts

`father doc dev --storybook --port=9003`

feat: Storybook support config port

---

README.md
packages/father-build/src/babel.ts
packages/father-build/src/fixtures/build/babel-normal/src/__test__/__snapshots__/index.test.js.snap
packages/father-build/src/fixtures/build/babel-normal/src/__test__/index.test.js

babel mode leave `__test__` dir not compiled

feat: add __test__ to babel ignore

---

README.md
packages/father-build/src/getRollupConfig.ts
packages/father-build/src/schema.test.ts
packages/father-build/src/schema.ts
packages/father-build/src/types.d.ts

Close https://github.com/umijs/father/issues/104.

feat: add include opt in rollup umd cjs use for project config

---

packages/father-build/src/babel.ts
packages/father-build/src/build.ts
packages/father-build/src/getBabelConfig.ts
packages/father-build/src/getRollupConfig.ts
packages/father-build/src/randomColor.ts
packages/father-build/src/registerBabel.ts
packages/father-build/src/rollup.ts
packages/father-build/yarn.lock

feat: improve log style

---

packages/father-build/src/fixtures/build/rollup-umd-css-extract-minFile/.fatherrc.js
packages/father-build/src/fixtures/build/rollup-umd-css-extract-minFile/expected/index.umd.css
packages/father-build/src/fixtures/build/rollup-umd-css-extract-minFile/expected/index.umd.js
packages/father-build/src/fixtures/build/rollup-umd-css-extract-minFile/expected/index.umd.min.css
packages/father-build/src/fixtures/build/rollup-umd-css-extract-minFile/expected/index.umd.min.js
packages/father-build/src/fixtures/build/rollup-umd-css-extract-minFile/src/foo.css
packages/father-build/src/fixtures/build/rollup-umd-css-extract-minFile/src/index.js
packages/father-build/src/getRollupConfig.ts

fix(father-build): css minify with umd file

---

packages/father/package.json
packages/father/src/doc/storybook-generator.ts

feat: support set storybook theme via process.env.STORYBOOK_THEME

---

packages/father-build/package.json
packages/father-build/src/fixtures/build/babel-ts-3.7-features/.fatherrc.js
packages/father-build/src/fixtures/build/babel-ts-3.7-features/expected/es/index.d.ts
packages/father-build/src/fixtures/build/babel-ts-3.7-features/expected/es/index.js
packages/father-build/src/fixtures/build/babel-ts-3.7-features/expected/lib/index.d.ts
packages/father-build/src/fixtures/build/babel-ts-3.7-features/expected/lib/index.js
packages/father-build/src/fixtures/build/babel-ts-3.7-features/src/index.ts
packages/father-build/src/getBabelConfig.ts

在 babel 官方支持之前先用这种方式支持一下 https://github.com/babel/babel/issues/10690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/father/166)

feat(father-build): support ts3.7 features for babel output

---

README.md

fix: readme __test__ show

---

packages/father-build/src/schema.ts

fix: umd source type check

---

.github/workflows/ci.yml
packages/father-build/src/fixtures/build/babel-runtimeHelpers/expected/es/index.js
packages/father-build/src/fixtures/build/babel-runtimeHelpers/expected/lib/index.js
packages/father-build/src/fixtures/build/babel-syntax/expected/index.esm.js
packages/father-build/src/fixtures/build/rollup-resolve-jsx/expected/index.esm.js
packages/father-build/src/fixtures/build/rollup-runtimeHelpers/expected/index.esm.js
packages/father-build/src/fixtures/build/rollup-runtimeHelpers/expected/index.js
packages/father-build/src/fixtures/build/rollup-svgr/dist/index.esm.js
packages/father-build/src/fixtures/build/rollup-svgr/expected/index.esm.js
packages/father-build/yarn.lock
packages/father/src/fixtures/e2e/normal/dist/index.esm.js
packages/father/src/fixtures/e2e/normal/expected/index.esm.js
packages/father/yarn.lock
yarn.lock

- any feature?
- close https://github.com/umijs/father/ISSUE_URL

fix: ci since babel upgraded

---

packages/father-build/package.json
packages/father-build/src/babel.ts

Same as #251 but for father 2.x

fix(babel): handle compile error to avoid watch exit

---

packages/father-build/src/schema.ts

fix: include type

---

packages/father-build/src/build.ts

pkg 某些情况下可能是一个包含 name 属性的对象
```
console.log(`${pkg ? `${randomColor(`${pkg}`)}: ` : ''}${msg}`);
```

lerna 模式 build 时控制台包名无法正确显示

---

packages/father-build/src/build.ts
packages/father-build/src/getRollupConfig.ts
packages/father-build/src/rollup.ts

修复lerna模式子项目没有tsconfig.json找不到父级tsconfig.json报错

---

README.md
packages/father-build/src/getUserConfig.ts
packages/father-build/src/schema.ts
packages/father-build/src/types.d.ts

injectCSS 现在只支持bool， rollup-plugin-postcss是可以支持函数的。

injectCSS支持函数类型

---

packages/father-build/package.json
packages/father-build/yarn.lock

chore: upgrade ajv@6.12.6

---

packages/father-build/package.json
packages/father-build/src/babel.ts
yarn.lock

支持babel打包下TypeScript的alias路径转relative路径

Support Bebal build typescript alias to relative path

---

packages/father-build/bin/father-build.js
packages/father-build/src/build.ts
packages/father-build/src/types.d.ts

feat(father-build): add  clean cli arg

---

docs/guide/esm-cjs.md

docs: update esm-cjs.md example

---

docs/guide/doctor.md

docs: correct typo in doctor

---

src/builder/bundless/index.ts

修复同时更改多个文件时，部分文件的输出会丢失的 bug，原因是错误的 debounce 逻辑导致部分文件变更被忽略了

fix: partial output lost when change multiple files at the same time

---

src/doctor/rules/CJS_IMPORT_ESM.ts
tests/doctor.test.ts

Close #624 
在找到好的实现方式前，暂时禁用 CJS_IMPORT_ESM 规则

fix: disable CJS_IMPORT_ESM rule

---

src/types.ts

修复 UMD 打包 externals 配置项的类型定义
Close #596

fix: correct umd externals config types

---

src/builder/bundle/index.ts

`ANALYZE=1` 环境变量支持对多 umd entry 做分析
Close #587

feat: support to analyze multi-entry for umd

---

.github/workflows/ci.yml
docs/config.md
package.json
pnpm-lock.yaml
src/builder/bundless/index.ts
src/builder/bundless/loaders/index.ts
src/builder/bundless/loaders/javascript/babel.ts
src/builder/bundless/loaders/javascript/esbuild.ts
src/builder/bundless/loaders/javascript/index.ts
src/builder/bundless/loaders/javascript/swc.ts
src/builder/bundless/loaders/types.ts
src/builder/bundless/parallelLoader.ts
src/builder/config.ts
src/features/configBuilder/configBuilder.ts
src/features/configPlugins/schema.ts
src/types.ts
tests/parallel.test.ts

supports parallel compilation bundless code.

feat: bunless parallel

---

bin/father.js
package.json
pnpm-lock.yaml

fix: remove v8-cache

---

examples/utoo-pack/.fatherrc.ts
src/builder/bundle/index.ts
src/builder/utils.ts
src/types.ts
tests/utoo-pack.build.test.ts

Change config filed from `utoo-pack` to `utoopack`(`.fatherrc.ts`):
As follows:
```ts
export default defineConfig({
umd: {
bundler: 'utoopack'
}
})
```

chore: update umd bundler config utoo-pack to utoopack

---

docs/config.md
src/builder/bundless/dts/index.ts
tests/config.test.ts
tests/fixtures/config/config-custom-tsconfig-name/.fatherrc.ts
tests/fixtures/config/config-custom-tsconfig-name/expect.ts
tests/fixtures/config/config-custom-tsconfig-name/src/exclude/index.ts
tests/fixtures/config/config-custom-tsconfig-name/src/index.ts
tests/fixtures/config/config-custom-tsconfig-name/tsconfig.build.json

close https://github.com/umijs/father/issues/800

feat: allow specify tsconfig name

---

examples/utoo-pack/.fatherrc.ts
package.json
pnpm-lock.yaml
src/builder/bundle/index.ts

release note refer: https://github.com/umijs/mako/releases/tag/utoopack-v0.0.1-alpha.40

chore: bump @utoo/pack to 0.0.1-alpha.40
