- .gitignore
- src/babel.ts
- src/build.ts
- src/fixtures/build/babel-typescript-template/.umirc.library.js
- src/fixtures/build/babel-typescript-template/expected/es/index.d.ts
- src/fixtures/build/babel-typescript-template/expected/es/index.js
- src/fixtures/build/babel-typescript-template/expected/lib/index.d.ts
- src/fixtures/build/babel-typescript-template/expected/lib/index.js
- src/fixtures/build/babel-typescript-template/src/index.ts
- template/tsconfig.json
Provides default ts config if `tsconfig.json` not provided.
ref `rc-tools`:
* https://github.com/react-component/rc-tools/blob/master/lib/getTSCommonConfig.js
* https://github.com/react-component/rc-tools/blob/master/config/tsconfig.json
cc @chenshuai2144
> feat: Support default `tsconfig.json` as template

- src/doc.ts
> feat: support 404 fallback mechanism while deploy docs

- src/build.test.ts
- src/build.ts
`.DS_Store` will exist in `packages` dir leading to a build error.
> fix: ignore pkg .DS_Store

- packages/father-build/src/getBabelConfig.ts
target 是 node 时 runtime helper 不能是 esm 格式
> fix(babel-config): only use es module with runtime plugin while target is browser

- packages/father/src/doc/docz-plugin-react-externals.ts
https://github.com/umijs/father/issues/15
增加`reactConfig`配置项，包含`react` & `reactDom`子项去自定义`react` & `react-dom`的url。如：
```
doc: {
reactConfig: {
react: xxxx,
reactDom: xxxx
}
}
```
> feat: Add reactConfig for udf react & reactDom url

- packages/father-build/package.json
- packages/father-build/src/getBabelConfig.ts
- packages/father/src/father.e2e.ts
通过环境变量 `COVERAGE` 控制是否加入 babel-plugin-istanbul 插件
> feat: use COVERAGE env variable to control babel plugin babel-plugin-istanbul

- packages/father-build/src/fixtures/build/babel-runtimeHelpers/.fatherrc.js
- packages/father-build/src/fixtures/build/babel-runtimeHelpers/expected/es/index.js
- packages/father-build/src/fixtures/build/babel-runtimeHelpers/expected/lib/index.js
- packages/father-build/src/fixtures/build/babel-runtimeHelpers/package.json
- packages/father-build/src/fixtures/build/babel-runtimeHelpers/src/index.js
- packages/father-build/src/getBabelConfig.ts
- packages/father-build/src/getRollupConfig.ts
使用babel 打cjs包 在开启runtimeHelpers情况下 不使用esm
Close #78
> fix: cjs babel do not use esm runtimeHelpers

- README.md
- packages/father-build/package.json
- packages/father-build/src/babel.ts
- packages/father-build/src/build.ts
- packages/father-build/src/fixtures/build/babel-cjs-lazy/.fatherrc.js
- packages/father-build/src/fixtures/build/babel-cjs-lazy/expected/lib/index.js
- packages/father-build/src/fixtures/build/babel-cjs-lazy/src/index.js
- packages/father-build/src/getBabelConfig.ts
- packages/father-build/src/schema.ts
- packages/father-build/src/types.d.ts
- packages/father-build/yarn.lock
可以让 umi 命令提速和解耦，比如，
1. `umi -v` 从 3.7s 提升到 0.7s
2. `umi block` 挂了不会影响 `umi dev`
3. `umi ui` 打开项目速度从 4-5 秒提升到 2 秒
> feat: support lazy require with cjs.lazy

- packages/father-build/src/babel.ts
- packages/father-build/src/rollup.ts
修复 umi 下执行 `y ui:build -w` 后按 Command+C，进程不会退出的问题。
> fix: close watcher for SIGINT

- packages/father/src/doc/storybook.ts
Storybook read the env variable as build variable. We need set this for `dev` mode.
> chore: Add env for storybook usage

- packages/father/package.json
- packages/father/src/doc/storybook-generator.ts
Fix the bug that fail to use `storybook` in Windows.
Related issues: https://github.com/umijs/father/issues/86
> fix(father): failed to resolve module in Windows

- packages/father-build/src/getRollupConfig.ts
`rollup-plugin-typescript2` find out `tsconfig` via method [findConfigFile](https://github.com/microsoft/TypeScript/blob/2d96a163d1a666e7b156c5597f3419ff8b560864/src/compiler/program.ts#L4), supporting bottom up search by default.
> feat: bottom-up search file `tsconfig.json`

- README.md
- packages/father-build/src/fixtures/build/rollup-umd-sourcemap/.fatherrc.js
- packages/father-build/src/fixtures/build/rollup-umd-sourcemap/expected/index.umd.js
- packages/father-build/src/fixtures/build/rollup-umd-sourcemap/expected/index.umd.js.map
- packages/father-build/src/fixtures/build/rollup-umd-sourcemap/src/index.js
- packages/father-build/src/getRollupConfig.ts
- packages/father-build/src/schema.test.ts
- packages/father-build/src/schema.ts
- packages/father-build/src/types.d.ts
umd格式，很多时候是用来单独在浏览器中运行的，因此添加sourcemap选项，以便调试代码
> feat: supported `umd.sourcemap` option

- packages/father-build/src/babel.ts
- packages/father-build/src/fixtures/build/babel-typescript/tsconfig.json
- packages/father-build/src/schema.test.ts
- `tsconfig.json` 不是严格的json, `tsc --init`生成的默认 tsconfig.josn 就带有很多注释。
这里将JSON.parse 换成ts自带的api，保证兼容。
- 另外修复一个小的测试bug。
> fix: parse tsconfig.josn error

- packages/father-build/src/fixtures/build/babel-runtimeHelpers/expected/es/index.js
- packages/father-build/src/fixtures/build/babel-runtimeHelpers/expected/lib/index.js
- packages/father-build/src/fixtures/build/babel-runtimeHelpers/package.json
- packages/father-build/src/fixtures/build/babel-runtimeHelpers/src/index.js
- packages/father-build/src/fixtures/build/babel-syntax/expected/index.esm.js
- packages/father-build/src/fixtures/build/rollup-resolve-jsx/expected/index.esm.js
- packages/father-build/src/fixtures/build/rollup-runtimeHelpers/expected/index.esm.js
- packages/father-build/src/fixtures/build/rollup-runtimeHelpers/expected/index.js
- packages/father-build/src/fixtures/build/rollup-svgr/dist/index.esm.js
- packages/father-build/src/fixtures/build/rollup-svgr/expected/index.esm.js
- packages/father-build/src/getBabelConfig.ts
- packages/father/src/fixtures/e2e/normal/dist/index.esm.js
- packages/father/src/fixtures/e2e/normal/expected/index.esm.js
close https://github.com/umijs/father/issues/224
参考 https://github.com/babel/babel/issues/10261 。
开启 [version](https://www.babeljs.cn/docs/babel-plugin-transform-runtime#version) 参数，解决 `ownKeys` 和 `_objectSpread` 没有走 @babel/runtime 的问题。比如：https://unpkg.com/browse/rc-select@11.1.0/es/generate.js
> feat: support babel runtime version

- packages/father-build/src/babel.ts
目前项目中使用father-build babel模式构建项目时，整体的项目构建会受到项目根目录babel.config.js的影响导致项目构建报错
babel.transform时增加configFile: false配置，让father-build babel模式构建时，不读取外部的babel.config.js配置文件，全采用babelOpts中的babel配置来构建
- 修改前：fatehr-build（2.x）构建外部有babel.config.js的工程构建报错
- 修改后：fork后修改了代码的fatehr-build（jianghe20200825-fix）构建外部有babel.config.js的工程成功（忽略了外部的babel.config.js）
> fix(): 解决father-build babel模式构建时会受外部babel.config.js影响导致babelOpts失效的问题

- packages/father/src/test.ts
修复 `father test` 命令传递 `glob` 和 `-w` 参数无效的问题，
相关 issue: #199
> fix(test): path & watch args not working bug (#199)

- packages/preset-built-in/package.json
- packages/preset-built-in/src/commands/build/babel.ts
修复 babel 模式且启用 watch 的情况下、TypeScript 类型检查错误会导致 father 的 watch 任务中断退出的问题。参考：https://github.com/gulpjs/gulp/issues/2111
watch 启动之后可以良好运行，但如果首次启动的时候就存在 TypeScript 编译错误，则还是需要手动重启；考虑到该场景很少，后续再想办法优化
> fix(babel): handle compile error to avoid watch exit

- packages/father-build/src/getRollupConfig.ts
修复 `cssModules` 无法对 `*.less` 文件进行 CSS Modules
> chore: cssModules not work

- circle.yml
CircleCI 从某个时间开始 yarn bootstrap 过程中会莫名 kill，怀疑是 node-sass 安装的问题，但尝试增加执行内存、切换 Node.js 版本号、延长 no_ouput_timeout 等都没有解决问题，且本地和其他 CI 平台无法复现
故切换到 npm 安装 + 使用 Node.js v14 以避开 CircleCI 挂掉的问题，真实原因仍然未知
> ci: fix circleci failed

- packages/father-build/src/babel.ts
- packages/father-build/src/build.ts
- packages/father-build/src/rollup.ts
- packages/father-build/src/types.d.ts
子进程的测试用例不太好写，可以用这个 file 来验证下
```js
require('father-build')
.default({
cwd: process.cwd(),
watch: true,
buildArgs: {
cjs: 'rollup',
esm: 'babel',
},
})
.then((cancel) => {
console.log('process should exit after 2000');
setTimeout(() => {
cancel();
}, 2000);
});
```
> feat: return dispose for cancel build watch

- packages/father-build/src/babel.ts
babel 模式下，https://github.com/umijs/father#%E5%85%B3%E4%BA%8E-babel-%E6%A8%A1%E5%BC%8F ，这些目录不会被编译到 es、lib 目录下，
希望添加一下 `__tests__` ，Jest 测试目录，除了使用 `__test__`，一般更习惯用 `__tests__` 。
> perf: add __tests__ dir in patterns

- packages/father-build/src/build.ts
传入的是opts.buildArgs 读取的是opts.rootConfig
> fix: 修复pkgs配置只在 father-build 生效

- packages/father-build/src/babel.ts
tsconfig  in src dir will be copied without compiled
> fix: babel build remove all tsconfig.json

- packages/father-build/src/rollup.ts
如果对构建顺序有要求（指定了 `pkgs`），例如：
```
{
pkgs: ['pkg-1', 'pkg-2']
}
```
此时，如果使用 `rollup.watch` 模式构建，在 `pkg-1` 尚未完成第一次构建的时候，就会开始 `pkg-2` 的构建。
因为对构建顺序有要求，所以会导致 `pkg-2` 构建失败。
---
同时，这个 PR 优化了控制台的输出。
> fix: rollup watch 模式的构建依赖问题

- packages/father-build/package.json
- packages/father-build/src/fixtures/build/babel-runtime-local/expected/es/index.js
- packages/father-build/src/fixtures/build/babel-runtime-local/expected/lib/index.js
- packages/father-build/src/fixtures/build/rollup-runtimeHelpers/expected/index.js
- packages/father-build/src/fixtures/build/rollup-umd-sourcemap/expected/index.umd.js.map
- yarn.lock
升级 `@babel/core` 和 `@babel/plugin-transform-runtime` 到 `7.18.x`，确保和无法锁住的间接依赖 `@babel/helpers` 能正常配合，避免产物中出现 inline 的 `regeneratorRuntime`。
为什么不全部 babel 依赖一起升级？试了下 polyfill 的变更比较多，大部分用例都挂了 + 要改一些配置才能消掉新增的 warning + 其他插件目前看起来没有影响，打算 father 4 再升了
> chore(deps): upgrade part of babel deps to 7.18

- src/builder/bundle/index.ts
- src/builder/index.ts
- src/commands/build.ts
umd 构建，持久化缓存要和 pkg.json 以及配置文件内容挂钩，否则改了配置文件再次打包仍然是旧的产物。
> fix(umd): webpack persistent cache deps

- src/builder/utils.ts
- tests/fixtures/build/build-sourcemap/expect.ts
- tests/fixtures/build/bundless-swc-sourcemap/expect.ts
修复bundleless模式下使用babel或者swc导致sourceMappingURL后缀错误 #553
> fix: sourcemap url

- pnpm-lock.yaml
- src/builder/bundle/index.ts
- src/builder/bundless/dts/index.ts
- src/builder/bundless/loaders/javascript/babel.ts
- src/builder/bundless/loaders/javascript/swc.ts
- src/builder/utils.ts
- tests/fixtures/build/automatic-jsx/package.json
- tests/fixtures/build/automatic-jsx/tsconfig.json
Bundless 的 babel & SWC、Bundle 的 Webpack 都优先使用 tsconfig.json 中的 jsx 配置来决定 React JSX 的转换方式
> refactor: react jsx runtime respect tsconfig.json

- src/builder/bundless/dts/index.ts
部分项目可能会用 tsc 检查作为 CI 的一部分，可能在配置里手动加上 `noEmit: true`，但这会导致 father 获取不到 ts program 的输出结果，所以加上警告以提示用户
> refactor: warn for noEmit when declaration is true

- src/cli/cli.ts
在 dev 命令中处理 Ctrl+C，避免用 pnpm 执行时被当做异常终止，抛出错误信息
Closing #573
> fix: handle SIGINT in dev to avoid pnpm exit with error

- src/builder/bundle/index.ts
- src/builder/bundless/dts/index.ts
- src/builder/bundless/index.ts
- src/builder/config.ts
- src/builder/index.ts
- src/cli/cli.ts
- src/cli/node.ts
- src/commands/build.ts
- src/commands/changelog.ts
- src/commands/dev.ts
- src/commands/generators/commitlint.ts
- src/commands/generators/eslint.ts
- src/commands/generators/jest.ts
- src/commands/generators/lint.ts
- src/commands/generators/stylelint.ts
- src/commands/generators/utils.ts
- src/commands/help.ts
- src/commands/release.ts
- src/features/depsOnDemand/swc.ts
- src/prebundler/index.ts
- src/utils.ts
- tests/utils.test.ts
基于 Umi logger 封装 father 的 logger，支持 4 个特性：
1. `logger.quietOnly.xx`，该日志仅在 quiet 模式下输出
2. `logger.quietExpect.xx`，该日志仅在非 quiet 模式下输出
3. `logger.setQuiet`，修改 quiet 状态
4. 在 NODE_ENV 为 development 时，自动给每条日志前面加上时间戳
所有用到 logger 的地方都根据实际需要做了调用调整，包一层 logger 的作用：
1. 能让 quiet 模式的输出更精简
2. 能对全部命令生效，并且最小改动
3. 时间戳方便 watch 时确认最近编译时间
效果：
> feat: improve logger for quiet and time prefix

- src/builder/bundle/index.ts
修复 umd 多 entry 的情况下，dev 构建只输出第一个 entry 产物的 bug
> fix: dist lost if multi-entry umd used in dev command

- src/builder/bundless/dts/index.ts
修复当项目依赖了 TypeScript 4.9.x 时，类型产物中的 `paths` 别名没有转换的问题
原因：[typescript-transform-paths](https://www.npmjs.com/package/typescript-transform-paths) 目前不支持 TypeScript 4.9，但也不会报错
解法：father 将自己依赖的 TypeScript 4.8.x 传给插件使用，确保插件拿到的 TypeScript 实例与 father 声明的一致
> fix: d.ts paths transform bug if project use ts 4.9.x

- src/builder/bundle/index.ts
father 禁用 svgr，所以在 bundle 模式下也将 svg 也当做普通图片资源处理，base64 or 转为独立文件
> feat: handle svg as normal image assets in bundle mode

- src/doctor/rules/PREFER_PEER_DEPS.ts
- tests/doctor.test.ts
- tests/fixtures/doctor/warns/package.json
新增 `PREFER_PEER_DEPS` doctor 规则，用于警告放入 `dependencies` 时有多实例风险的依赖，比如 `react`、`antd`
> feat: add PREFER_PEER_DEPS doctor rule

- src/doctor/index.ts
- tests/fixtures/doctor/errors/.fatherrc.ts
- tests/fixtures/doctor/errors/src/ignore.ts
修复 bundless `ignores` 配置中的文件仍然会被 doctor 检查的 bug
> fix: bundless ignore files are still checked in doctor

- .github/workflows/ci.yml
- src/doctor/index.ts
- src/doctor/rules/CJS_IMPORT_ESM.ts
- src/doctor/rules/PHANTOM_DEPS.ts
- src/doctor/utils.ts
- src/types.ts
- tests/config.test.ts
- tests/deps.test.ts
- tests/dev.test.ts
- tests/doctor.test.ts
- tests/fixtures/doctor/errors/node_modules/esm/index.js
- tests/fixtures/doctor/errors/node_modules/esm/package.json
- tests/fixtures/doctor/errors/package.json
- tests/fixtures/doctor/errors/src/index.ts
新增 `CJS_IMPORT_ESM` doctor 规则，用于检测 cjs 产物里引入的 pure esm 依赖，这会导致 NPM 包发布后在 Node.js 运行时报错，类似：
```bash
Uncaught:
Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/esm.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
```
> feat: add CJS_IMPORT_ESM doctor rule

- boilerplate/src/index.ts
- boilerplate/template/.fatherrc.ts.tpl
- src/types.ts
不知是否刻意设置 如果是 建议更改模板 加上 deps:{ }
> fix: 'prebundle' is preset in correct env template

- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/builder/bundle/index.ts
- src/builder/bundless/loaders/javascript/babel.ts
- src/builder/utils.ts
- tests/fixtures/build/styled-components/.fatherrc.ts
- tests/fixtures/build/styled-components/expect.ts
- tests/fixtures/build/styled-components/package.json
- tests/fixtures/build/styled-components/src/index.ts
- tests/g.commitlint.test.ts
支持对 styled-components 项目启用 babel-plugin-styled-components，并自动根据包名设置 namespace
> feat: enable babel plugin for styled-components project

- src/builder/bundless/dts/index.ts
> fix: dts lost when rebuild with incremental cache

- jest.config.ts
- tests/dev.test.ts
提升 Windows CI 的测试成功率，之前经常失败但重试又能成功的原因是，在配置文件修改后自动重新构建的 case 里，只等待了 5s，但验证下来 Windows CI 的平均重启构建的时间就是 5s 左右，所以只要执行时间稍长就会失败
解法：把等待时间提升到 6s
> ci: improve sucess rate for windows ci

- src/builder/bundless/dts/index.ts
- tests/fixtures/build/bundless-diff-dts/.fatherrc.ts
- tests/fixtures/build/bundless-diff-dts/expect.ts
- tests/fixtures/build/bundless-diff-dts/src/ignore.ts
- tests/fixtures/build/bundless-diff-dts/src/index.ts
- tests/fixtures/build/bundless-diff-dts/tsconfig.json
修复 esm 和 cjs 有不同的 `ignores` 配置时，cjs 产物中部分 `.d.ts` 会丢失的问题
> fix: dts lost when esm and cjs has different ignores

- src/builder/bundless/loaders/javascript/babel.ts
修复意外识别 `babel.config.js` 配置文件的问题
Close #651
> fix: should not read babel config file

- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
问题描述：pnpm版本有问题。
`pnpm.lock`文件里面的lockfileverison是6.0。这是`~pnpm8.5.0`的默认版本，`pnpm.8.6.0`开始这个字段默认是`6.1`
`package.json`文件里面声明的`packageManager`是`7.3.0`，在使用`corepack`管理包管理器的时候在本仓库目录下会强制置`pnpm`为`7.3.0`，导致很多问题
在ci的时候声明的`pnpm`版本为`8`会解析到最新的8版本，也就是`8.6.1`，ci的时候`pnpm`会默认加上`--frozen-lockfile`参数所以没问题，本地使用`pnpm@8.6.1`会导致lock被更改， [action链接](https://github.com/umijs/father/actions/runs/5195740784/jobs/9368752425)
解决：
先将版本统一为lock文件指定的pnpm版本，也就是`8.5.1`
> chore: set pnpm version to 8.6.2

- src/prebundler/config.ts
- src/utils.ts
- tests/fixtures/prebundle/builtin-module/.fatherrc.ts
- tests/fixtures/prebundle/builtin-module/expect.ts
- tests/fixtures/prebundle/builtin-module/package.json
- tests/utils.test.ts
支持对 `url`、`util` 等跟 `builtin-module` 同名的库进行预编译。
之前会报错，因为 `require.resolve('url')` 返回的 `entry` 是 `url`， 传递给ncc会报错。
> feat: support pre-bundle for legacy built-in-modules

- src/builder/utils.ts
优化 React JSX 类型的识别逻辑，以满足某些场景下依赖声明里不存在 react 的场景（比如使用 `@emotion/react`），以及某些场景下不需要转换 React JSX 的场景，详细差异如下：
改动前：先判定是否存在 react 的依赖声明，再优先使用 tsconfig 的 jsx 设置，最后兜底根据 react 版本号决定 jsx 设置，无论如何都会启用 `@babel/preset-react`
改动后：优先使用 tsconfig 的 jsx 设置，再根据 react 版本号决定 jsx 设置，如果两者都不存在则不会启用 `@babel/preset-react`
> refactor: improve logic to set react jsx type

- package.json
- pnpm-lock.yaml
升级 TypeScript 到 `~5.0.4`，继续维持与 `@microsoft/api-extractor` 相同的版本声明，避免同时安装多个版本的 `typescript`
Close #680
> feat: upgrade typescript to ~5.0.4

- docs/config.md
- src/builder/utils.ts
降级 SWC 作为 transformer 时 browser 产物的 targets 为 `{ ie: 11 }`，确保产物是 ES5，与 Babel 保持一致。
补充说明：esbuild 的 targets 之所以是 chrome 版本号，是因为很多高级语法它最多[只能转换到 ES6](https://esbuild.github.io/api/#target)，如果设置为 `{ ie: 11 }` 会报错，但 SWC 有这个能力，所以没必要和 esbuild 一样使用 chrome 版本号
cc @MadCcc @huarse
> refactor: downgrade browser targets for swc transformer

- docs/config.md
- src/builder/utils.ts
降级 esbuild 作为 transformer 时 browser 产物的 targets 为 `{ chrome: 51 }`，确保产物是 ES6，与 father 4 发布时保持一致，这也是 esbuild 能安全转换的最低 targets。
cc @huarse
> refactor: downgrade browser targets for esbuild transformer

- src/builder/bundless/dts/index.ts
- src/builder/utils.ts
修复存在持久缓存已存在且重复保存某个文件但不修改内容时，`.d.ts` 不会生成的问题，另外修改 `.tsbuildinfo` 文件的位置强行让存量项目的 tsc 缓存失效实现缓存重建。
原因是 tsc 的 incremental 模式不会生成未变更的文件，father 使用持久缓存补齐这些文件，但缓存 key 不是依据内容哈希而是文件修改时间，所以在文件重复保存时，tsc 认为文件没有变更（应该是以哈希判断？）所以不会生成，father 又从持久缓存中找不到（以时间戳查找）对应内容无法补齐文件，最终导致 `.d.ts` 丢失。
解法是 father 对 `.d.ts` 的缓存 key 改为内容哈希，确保重复保存时也能命中。
Close #669
> fix: dts lost in re-compilation if save file with same content

- src/doctor/index.ts
- tests/fixtures/doctor/health/src/test.d.ts
doctor 在收集源代码文件的时候过滤掉 `.d.ts` 文件，两个原因：
1. doctor 预期是只查 JavaScript 和 TypeScript 源代码，类型文件不在目前的设计内
2. esbuid 对 `.d.ts` 文件内容的报错不如 tsc 人性化，不如交给 IDE 或交给 build 来提示
> refactor: skip d.ts files when doctor parsing

- src/builder/bundless/dts/index.ts
修复在 tsconfig 变更后，d.ts 文件可能丢失的问题，引发该问题的上下文如下：
1. father 4.2 使用了 tsc 的 incremental 模式做增量编译，部分 tsconfig 的修改可能会被 tsc 判定为不需要重新编译
2. father 构建前默认清空输出目录，而上一条 tsc 又可能不会重新输出文件，所以 father 利用持久缓存做了文件补齐，参考 https://github.com/umijs/father/pull/649 https://github.com/umijs/father/pull/656
3. father 持久缓存的 key 由文件 path、contenthash 和 tsconfig 组成，这意味着只要 tsconfig 发生变更这份缓存就失效了，也就无法为 1 做文件不齐，导致 d.ts 文件丢失
解决方案：将 father 持久缓存 key 中的 tsconfig 去掉，缓存失效与否以 path 和 contenthash 为准；另外手动让 tsc 缓存失效，避免用户更新依赖但未删除 `node_modules/.cache` 的时候出现异常情况
这里无需担心缓存错乱的问题，几种带缓存构建的情况：
1. 文件未变 + tsconfig 变，tsc 就会重新编译输出新的产物，father 也会用这份新的结果覆盖旧的缓存
2. 文件变 + tsconfig 变，tsc 会重新编译输出新的产物，father 也会建立新的缓存
3. 文件未变 + tsconfig 未变，tsc 不会输出产物，father 会用持久缓存补齐产物
Close #698
> fix: d.ts may lost if tsconfig changed

- src/builder/bundless/dts/index.ts
- src/builder/bundless/loaders/index.ts
- src/builder/bundless/loaders/javascript/index.ts
- tests/fixtures/build/bundle-alias-tsconfig/tsconfig.json
- tests/fixtures/build/bundle-targets/src/index.ts
- tests/fixtures/build/bundless-alias/tsconfig.json
- tests/fixtures/build/bundless-babel-targets/src/index.ts
- tests/fixtures/build/bundless-diff-dts/tsconfig.json
- tests/fixtures/build/bundless-esbuild-targets/src/index.ts
- tests/fixtures/build/bundless-include-dts/.fatherrc.ts
- tests/fixtures/build/bundless-include-dts/expect.ts
- tests/fixtures/build/bundless-include-dts/global.d.ts
- tests/fixtures/build/bundless-include-dts/src/index.ts
- tests/fixtures/build/bundless-include-dts/tsconfig.json
- tests/fixtures/build/bundless-outer-paths/tsconfig.json
- tests/fixtures/build/bundless-swc-alias/tsconfig.json
- tests/fixtures/build/bundless-swc-targets/src/index.ts
- tests/fixtures/build/tsconfig.json
修复在生成 d.ts 时，通过 tsconfig include 的额外类型比如 `global.d.ts` 丢失导致编译报错的问题
Close #704
> fix: include types lost when generating dts

- src/builder/bundless/dts/index.ts
- tests/fixtures/build/bundless-omit-dts-error/.fatherrc.ts
- tests/fixtures/build/bundless-omit-dts-error/docs/error.ts
- tests/fixtures/build/bundless-omit-dts-error/expect.ts
- tests/fixtures/build/bundless-omit-dts-error/src/demos/error.ts
- tests/fixtures/build/bundless-omit-dts-error/src/index.ts
- tests/fixtures/build/bundless-omit-dts-error/tsconfig.json
d.ts 生成的时候，忽略不在 bundless 文件列表中的类型错误，比如 `demos`、`config` 之类的
动机：father 仅抛出影响产物的类型错误，项目全量的类型错误仍然是 tsc 的职责，否则会引起多数项目构建失败
Close #710
> fix: omit dts errors that not in the built files

- docs/guide/doctor.md
- src/builder/bundless/dts/index.ts
- src/doctor/rules/TSCONFIG_RISK.ts
- tests/doctor.test.ts
- tests/fixtures/doctor/errors/tsconfig.json
新增 `TSCONFIG_RISK` doctor 规则，用于检查 tsconfig.json 配置中存在的风险，目前支持检测如下风险：
1. 当 `compilerOptions.declaration` 启用时，如果配置了 `include` 且没有包含任何 bundless 构建的源文件，则认定为存在 `.d.ts` 产物缺失风险，会进行报错
动机：主要是为了消除 #704  带来的负面影响，答疑中碰到了有项目的 `include` 配置项里包含源码目录，但又在消费 `.d.ts` 产物的情况，升级到 4.3.3 后会出现 `.d.ts` 产物缺失，所以利用 doctor 规则做一层拦截
> feat: add TSCONFIG_RISK doctor rule

- src/builder/bundless/dts/index.ts
修复超出 cwd 的 tsconfig `paths` 会出现模块找不到的类型错误的问题。
背景是 father 会在 d.ts 生成的时候自动替换 cwd 内的 `paths` 为相对路径，确保 d.ts 产物中的路径是可以被 resolve 的；但同时又会保留 cwd 之外的 `paths`，因为 monorepo 场景下会引用其他的子包，不能用相对路径去 resolve。
问题原因是之前 father 排除 cwd 之外的方式是把 tsconfig 中的部分 `paths` 删掉后再给 ts compiler，最后由 ts 插件来转换，但这其实会引起 `paths` 对应模块找不到的错误，而之前没报错是因为 4.3.2 之前有很多错误没抛出，ref: #701 。
解决方案是 father 保留原始的 tsconfig `paths` 给 ts compiler 确保编译过程中的类型完整，但对 ts 插件消费的 `paths` 做特殊处理，排除掉 cwd 之外的 paths。
> fix: tsconfig paths has type error if out of cwd

- src/builder/bundless/dts/index.ts
修复解析 `typeRoots` 的默认行为与 tsc 不一致的问题。
问题触发的情形：在 monorepo 使用根目录 tsconfig.json 的情况下，tsc 的 `typeRoots` 默认从根目录开始解析，仅包含根目录的 `node_modules/@types`，但 father 由于没有指定 `configFilePath` 则会从 cwd 开始解析，将会包含子包的 `node_modules/@types`，与 tsc 的差异行为会导致某些 IDE 不报错的情形但 father d.ts 生成报错，详细 case 可参考下方 issue。
Close #713
> fix: type roots behavior is inconsistent with tsc

- src/builder/bundless/dts/index.ts
修复前序 d.ts 编译失败时部分 d.ts 丢失的问题。
原因是 father 启用了 ts 的 incremental 特性，它会自动增量编译文件，即便前序 d.ts 编译时部分源代码的类型有误，在第二次编译时它也会尽可能少地重新编译文件；father 会用持久缓存对这些不再重复编译的 d.ts 做补齐，但缓存写入逻辑仅在不存在类型诊断错误时才会执行，和 ts 的 incremental 行为不一致，最终导致产物中丢失部分 d.ts 文件。
解法是把写缓存的逻辑提前到检查类型诊断错误之前，无论如何都写入缓存。
cc @zombieJ
> fix: dts may lost if another dts has error in last time

- src/builder/bundle/index.ts
- src/builder/bundless/loaders/index.ts
- src/doctor/parser.ts
使用 content hash 作为缓存键，替代原有的 mtime，这样 CI 环境也可以将 cache 复用
顺便修正了 bundle 模块源码中的变量名，由于不影响用户使用就不新开 PR 处理了，Close #709
> refactor: use hash instead mtime for cache key

- examples/normal/package.json
- src/commands/dev.ts
目前开发场景下可能会存在不需要`clean dist`目录的情况，正如https://github.com/umijs/father/issues/693#issuecomment-1674457219 所言当我在umi项目中对father的构建产物进行联调时，father的重新启动dev会造成umi的程序崩溃。
在某些重启father dev的场景下可能没有对`umirc`配置进行改变，所以不想把umi的服务关掉再启动，这会省一些时间。
Close https://github.com/umijs/father/issues/693
> feat: support --no-clean for dev command

- src/builder/bundle/index.ts
修正 umd 构建持久缓存的位置，从 `node_modules/.cache/bundler-webpack` 修正为 `node_modules/.cache/father/bundler-webpack`，之前的配置方式不对所以自定义缓存位置没有生效
为什么要改目录？方便统一管理以及避免与 umi 项目一起使用时出现冲突
cc @hualigushi
> fix: correct umd cache directory

- src/builder/bundless/loaders/index.ts
- src/doctor/parser.ts
- src/utils.ts
修复 bundless 的持久缓存可能损坏导致下一次构建直接报错的问题
原因是写缓存的操作是异步进行的，会出现在内容还未完全写入文件系统的时候就遇到 dts error 进程退出，导致缓存内容不可用；解决方案是 bundless loader 处理文件时，等缓存完全写入后再 resolve，这样 dts 始终作为 loader 的后置逻辑执行，即便异常终止也不会影响 loader 缓存的有效性
cc @hualigushi
> fix: bundless cache maybe broken if has dts error

- src/builder/bundless/index.ts
修复在某些特殊文件系统（比如 CloudIDE）中会 watch 到临时文件，然后尝试读取导致报错的问题，错误类似：
```bash
error - ENOENT: no such file or directory, open '/path/to/index.tsx.450062575'
```
解法是使用 `awaitWriteFinish` 等文件稳定了再触发事件，目前检测时间间隔设置得很小，所以对 watch 性能的影响应该较小
> fix: ignore fs-specific tmp files in watch mode

- src/builder/bundle/index.ts
- src/builder/bundless/dts/index.ts
- src/constants.ts
- src/utils.ts
支持通过环境变量 `FATHER_CACHE_DIR` 修改持久缓存目录位置
> feat: allow set fs cache dir by env

- package.json
- pnpm-lock.yaml
- src/builder/bundle/index.ts
- src/builder/bundless/loaders/javascript/babel.ts
修复从 `@umijs/babel-preset-umi@4.0.88` 开始移除 `babel-plugin-styled-components`，导致 father 此前提供的 styled-components 插件自动启用的能力不工作的问题，ref: https://github.com/umijs/father/pull/639
> fix: internal styled-components babel plugin lost since umi@4.0.88

- package.json
- pnpm-lock.yaml
参考 #682 升级typescript和@microsoft/api-extractor的版本。
在项目中使用`father bulid`报错，使用tsc构建正常。
Demo：
```ts
export function styleMap(cssStyleRule: CSSStyleRule) {
return cssStyleRule.styleMap;
}
```
目前father中依赖的ts仅支持5.0.X，此时`CSSStyleRule`类型上并没有styleMap，在ts后续版本中已经更新了类型定义。
期望升级father依赖的ts版本，使构建不报错。
> feat: upgrade typescript to ~5.3.3

- src/doctor/rules/PACK_FILES_MISSING.ts
修复 `father doctor` 的 `PACK_FILES_MISSING` 规则在扫描 prebundle 的 dts 产物时出现错误结果的问题
> fix: wrong doctor missing rule result for prebundle dts files

- src/doctor/index.ts
- tests/fixtures/doctor/errors/src/component.tsx
- tests/fixtures/doctor/errors/src/index.ts
修复 docker 检查中的 import 相关规则对 `tsx` 和 `jsx` 文件不生效的问题
> fix: doctor import checkups is not work for jsx and tsx files

- package.json
- pnpm-lock.yaml
- src/builder/bundless/loaders/javascript/esbuild.ts
不再从 umi/bundler-utils 引入 esbuilder , 因为umijs 升级 esbuilder -> 0.2+ 后产物与 0.17+ 存在差异, 无法运行.
> chore: lock esbuild@0.17.19

- .github/workflows/ci.yml
- src/utils.ts
- tests/fixtures/doctor/health/src/index.ts
修复 `PHANTOM_DEPS` 不支持 Node.js 内置模块的问题，现在遇到 `node:fs` 的引入会判定为幽灵依赖
> fix: doctor PHANTOM_DEPS rule cannot works with node:*

- package.json
- pnpm-lock.yaml
- tsconfig.json
升级 TypeScript 到 5.4.2 以获得 `Array.isArray` 情形下更好的推导能力，例如 [这个场景](https://www.typescriptlang.org/play/?ts=5.3.3#code/GYVwdgxgLglg9mABAIwBQEMBciDOUBOMYA5ogD64FHEDaAugJSIDeAUIh4jMIqgIQBBfPnQBPAHQwcQkaIwMmbTssTpEAXkQ10dANztOAX1YGO9ccDj4AouggALVKibqAfC1Mr04nAAcANjAQAKaoAAwANIgAjAz6yoZxrIZAA) 在 5.3.3 下就无法正确推导成数组，但从 5.4.x 开始就可以
- 为什么不是最新版（5.7.3）？father 需要保持与 @microsoft/api-extractor 相同的 TypeScript 版本以避免多个 TypeScript 导致安装体积膨胀，最新版 @microsoft/api-extractor@7.49.2 依赖的是 TypeScript 5.7.2
- 为什么不是 5.7.2？尝试升级后发现要连带升级 typescript-transform-paths，但该插件存在用法上的 Breaking Change，这会扩大改造面导致 PR 膨胀，这个任务交给 @Jinbao1001 跟进了，father 落后最新 TypeScript 有点多
- 为什么是 5.4.2？这是 @microsoft/api-extractor 在升级 TypeScript 5.7.2 前最近的版本，刚好能解原始问题，且能与当前版本 typescript-transform-paths 正常工作
> chore: upgrade typescript to 5.4.2

- docs/config.md
- src/builder/bundle/index.ts
- src/features/configPlugins/schema.ts
- src/types.ts
Ref:
https://github.com/ant-design/x/pull/229
https://github.com/umijs/umi/issues/12803
cc @afc163 
---
Config.
```ts
export default {
umd: {
transformRuntime: {
absoluteRuntime: process.cwd(),
},
}
}
```
Before:
After:
> feat: add transformRuntime config for bundle builder
